export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
export const ERROR_COMMENTS = "ERROR_COMMENTS";

export const REQUEST_CREATE_COMMENT = "REQUEST_CREATE_COMMENT";
export const RECEIVE_CREATE_COMMENT = "RECEIVE_CREATE_COMMENT";
export const ERROR_CREATE_COMMENT = "ERROR_CREATE_COMMENT";