// 3.1
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const ERROR_POSTS = 'ERROR_POSTS';

//3.2
export const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST';
export const SUCCESS_DELETE_POST = 'SUCCESS_DELETE_POST';
export const ERROR_DELETE_POST = 'ERROR_DELETE_POST';
export const CLEAR_DELETE_SUCCESS = 'CLEAR_DELETE_SUCCESS';

// 4. Get one post
export const REQUEST_POST = 'REQUEST_POST';
export const RECEIVE_POST = 'RECEIVE_POST';
export const ERROR_POST = 'ERROR_POST';

// 4 Updating
export const REQUEST_UPDATE_POST = 'REQUEST_UPDATE_POST';
export const RECEIVE_UPDATE_POST = 'RECEIVE_UPDATE_POST';
export const ERROR_UPDATE_POST = 'ERROR_UPDATE_POST';

// 4. Creating
export const REQUEST_CREATE_POST = 'REQUEST_CREATE_POST';
export const RECEIVE_CREATE_POST = 'RECEIVE_CREATE_POST';
export const ERROR_CREATE_POST = 'ERROR_CREATE_POST';
